import React, {useEffect, useMemo, useRef, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, CalendarClock, CheckCircle2, ChevronRight, Copy, Download, FileJson, LayoutDashboard, ListChecks, Lock, Plus, Repeat, RotateCcw, Search, ShieldCheck, Tags, Trash2, Upload, Wallet, X } from 'lucide-react';
import './styles.css';

const COLORS=['#3b82f6','#22c55e','#ec4899','#facc15','#ef4444','#d946ef','#8b5cf6','#60a5fa','#14b8a6','#fb923c','#a3e635','#0f766e','#fb7185','#7dd3fc','#94a3b8'];
const uid=()=>crypto?.randomUUID?.()||Math.random().toString(36).slice(2,10);
const today=()=>new Date().toISOString().slice(0,10);
const monthKey=(d=new Date())=>d.toISOString().slice(0,7);
const eur=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v||0));
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const daysInMonth=m=>new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate();
const dayOfMonth=()=>new Date().getDate();
const parseEuro=v=>{let s=String(v??'').replace(/[€\s]/g,'').trim(); if(!s)return 0; if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.'); else if(s.includes(','))s=s.replace(',','.'); const n=Number(s); return Number.isFinite(n)?n:0};
const normDate=v=>{const s=String(v??'').trim(); if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s; const m=s.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})$/); if(m){const y=m[3].length===2?'20'+m[3]:m[3]; return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`} const d=new Date(s); return Number.isNaN(d)?today():d.toISOString().slice(0,10)};
const prevMonth=m=>{const d=new Date(Number(m.slice(0,4)),Number(m.slice(5,7))-2,1); return monthKey(d)};

function parseCsv(text){const rows=[];let row=[],cur='',q=false;const first=text.split(/\r?\n/)[0]||'';const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';for(let i=0;i<text.length;i++){const ch=text[i],nx=text[i+1];if(ch==='"'&&q&&nx==='"'){cur+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===sep&&!q){row.push(cur);cur='';continue}if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cur);cur='';if(row.some(x=>String(x).trim()))rows.push(row.map(x=>String(x).trim()));row=[];continue}cur+=ch}row.push(cur);if(row.some(x=>String(x).trim()))rows.push(row.map(x=>String(x).trim()));return rows}

const defaultCats=[['Spesa',400,'variable'],['Bar / Colazioni / Snack',250,'variable'],['Asporto / Delivery',200,'variable'],['Casa',160,'fixed'],['Affitto',650,'fixed'],['Bollette',90,'fixed'],['Trasporti',70,'variable'],['Salute',50,'variable'],['Shopping / Personale',50,'variable'],['Tempo Libero',30,'variable'],['Abbonamenti',25,'fixed'],['Rate / Finanziamenti',10,'fixed'],['Regali',10,'variable'],['Viaggi',10,'variable'],['Varie / Altro',10,'variable']].map((x,i)=>({id:uid(),name:x[0],budget:x[1],kind:x[2],type:'expense',color:COLORS[i%COLORS.length]}));
const demoTx=[{id:uid(),date:today(),description:'Stipendio',categoryId:'income',type:'income',amount:1950,notes:'Entrata ricorrente'}];
[387,240,200,150,114,80,60,48,40,25,20,6,2,0,0].forEach((a,i)=>{if(a)demoTx.push({id:uid(),date:today(),description:defaultCats[i].name,categoryId:defaultCats[i].id,type:'expense',amount:a,notes:''})});
const defaultData={version:11,categories:defaultCats,transactions:demoTx,recurrences:[{id:uid(),description:'Stipendio',categoryId:'income',type:'income',amount:1950,day:1,active:true},{id:uid(),description:'Affitto',categoryId:defaultCats[4].id,type:'expense',amount:650,day:1,active:true}],settings:{pin:'',lastCategoryId:defaultCats[0].id,dirtyCount:0}};

function useData(){const [data,setData]=useState(()=>{try{return {...defaultData,...JSON.parse(localStorage.getItem('budgetflow')||'null')}}catch{return defaultData}});useEffect(()=>{localStorage.setItem('budgetflow',JSON.stringify({...data,version:11}));},[data]);return [data,setData]}
function lastBackup(){return localStorage.getItem('budgetflow_last_backup')||''}
function daysFrom(iso){return iso?Math.floor((Date.now()-new Date(iso).getTime())/86400000):999}
function download(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function App(){
 const [data,setData]=useData(); const [tab,setTab]=useState('dashboard'); const [month,setMonth]=useState(monthKey()); const [modal,setModal]=useState(null); const [query,setQuery]=useState(''); const [selected,setSelected]=useState([]); const [lastB,setLastB]=useState(lastBackup()); const [locked,setLocked]=useState(Boolean(data.settings?.pin)); const [pinTry,setPinTry]=useState(''); const [preview,setPreview]=useState(null);
 const cats=data.categories||[]; const txAll=data.transactions||[]; const monthTx=txAll.filter(t=>String(t.date).startsWith(month));
 const expenseCats=cats.filter(c=>c.type==='expense');
 const stats=useMemo(()=>{const budget=expenseCats.reduce((s,c)=>s+Number(c.budget||0),0);const income=monthTx.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0);const spent=monthTx.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0);let byCat=expenseCats.map(c=>{const spent=monthTx.filter(t=>t.type==='expense'&&t.categoryId===c.id).reduce((s,t)=>s+Number(t.amount),0);return{...c,spent,diff:Number(c.budget||0)-spent,pct:c.budget?spent/c.budget*100:0,share:spent?0:0}}).sort((a,b)=>b.spent-a.spent);byCat=byCat.map(c=>({...c,share:spent?c.spent/spent*100:0}));return{budget,income,spent,remaining:budget-spent,balance:income-spent,byCat}},[monthTx,cats]);
 const prev=useMemo(()=>{const p=prevMonth(month);return txAll.filter(t=>String(t.date).startsWith(p)&&t.type==='expense').reduce((m,t)=>({...m,[t.categoryId]:(m[t.categoryId]||0)+Number(t.amount)}),{})},[txAll,month]);
 const due=daysFrom(lastB)>=7;
 useEffect(()=>{ if(due && !sessionStorage.getItem('bf_backup_popup')){sessionStorage.setItem('bf_backup_popup','1'); setModal({type:'backupReminder'});} },[]);
 const touch=()=>setData(d=>({...d,settings:{...d.settings,dirtyCount:(d.settings?.dirtyCount||0)+1}}));
 const saveTx=t=>{setData(d=>({...d,transactions:t.id?d.transactions.map(x=>x.id===t.id?t:x):[{...t,id:uid()},...d.transactions],settings:{...d.settings,lastCategoryId:t.categoryId,dirtyCount:(d.settings?.dirtyCount||0)+1}}));setModal(null)};
 const delTx=ids=>{if(!ids.length)return;if(confirm(`Eliminare ${ids.length} transazioni?`)){setData(d=>({...d,transactions:d.transactions.filter(t=>!ids.includes(t.id)),settings:{...d.settings,dirtyCount:(d.settings?.dirtyCount||0)+1}}));setSelected([])}};
 const duplicate=t=>saveTx({...t,id:undefined,date:today(),description:t.description+' copia'});
 const saveCat=c=>{setData(d=>({...d,categories:c.id?d.categories.map(x=>x.id===c.id?c:x):[...d.categories,{...c,id:uid()}],settings:{...d.settings,dirtyCount:(d.settings?.dirtyCount||0)+1}}));setModal(null)};
 const delCat=id=>{if(confirm('Eliminare categoria e transazioni collegate?'))setData(d=>({...d,categories:d.categories.filter(c=>c.id!==id),transactions:d.transactions.filter(t=>t.categoryId!==id)}))};
 const copyPrevBudget=()=>{const map={};txAll.filter(t=>String(t.date).startsWith(prevMonth(month))&&t.type==='expense').forEach(t=>map[t.categoryId]=(map[t.categoryId]||0)+Number(t.amount));setData(d=>({...d,categories:d.categories.map(c=>c.type==='expense'?{...c,budget:map[c.id]||c.budget}:c)}));};
 const exportCsv=()=>{const rows=[['Data','Descrizione','Categoria','Tipo','Importo','Note'],...txAll.map(t=>[t.date,t.description,cats.find(c=>c.id===t.categoryId)?.name||'Accrediti',t.type,t.amount,t.notes||''])];download('budgetflow-transazioni.csv',rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')};
 const makeBackup=()=>{download(`budgetflow-backup-${today()}.json`,JSON.stringify({app:'BudgetFlow',version:11,createdAt:new Date().toISOString(),data},null,2));localStorage.setItem('budgetflow_last_backup',new Date().toISOString());setLastB(lastBackup());setData(d=>({...d,settings:{...d.settings,dirtyCount:0}}));setModal(null)};
 const restoreBackup=async f=>{if(!f)return;const obj=JSON.parse(await f.text());if(!obj?.data?.transactions||!obj?.data?.categories)return alert('Backup non valido');if(confirm(`Ripristinare backup del ${new Date(obj.createdAt||Date.now()).toLocaleString('it-IT')}?`)){setData({...defaultData,...obj.data});setModal(null)}};
 const prepareCsv=async f=>{if(!f)return;const rows=parseCsv(await f.text());const header=(rows[0]||[]).map(norm);const idx=names=>names.map(norm).map(n=>header.indexOf(n)).find(i=>i>=0);const amountI=idx(['importo','amount','valore','spesa']);if(amountI===undefined)return alert('Serve una colonna Importo');const dateI=idx(['data','date']),descI=idx(['descrizione','description','causale','nome']),catI=idx(['categoria','category']),typeI=idx(['tipo','type']),notesI=idx(['note','notes']);const mapped=rows.slice(1).map((r,i)=>{const rawType=norm(typeI!==undefined?r[typeI]:'');const amount=parseEuro(r[amountI]);const catName=catI!==undefined?r[catI]:'Varie / Altro';const type=rawType.includes('entr')||rawType==='income'||norm(catName).includes('accredit')?'income':'expense';return{id:uid(),date:normDate(dateI!==undefined?r[dateI]:today()),description:(descI!==undefined?r[descI]:'Import CSV')||'Import CSV',categoryName:catName,type,amount:Math.abs(amount),notes:notesI!==undefined?r[notesI]:'',sourceRow:i+2}}).filter(x=>x.amount);const existing=new Set(txAll.map(t=>`${t.date}|${norm(t.description)}|${t.amount}|${t.type}`));setPreview({rows:mapped,duplicates:mapped.filter(t=>existing.has(`${t.date}|${norm(t.description)}|${t.amount}|${t.type}`)).length})};
 const confirmImport=()=>{const rows=preview.rows;setData(d=>{const categories=[...d.categories];const existing=new Set(d.transactions.map(t=>`${t.date}|${norm(t.description)}|${t.amount}|${t.type}`));const transactions=[];for(const r of rows){if(existing.has(`${r.date}|${norm(r.description)}|${r.amount}|${r.type}`))continue;let categoryId='income';if(r.type==='expense'){let c=categories.find(c=>norm(c.name)===norm(r.categoryName));if(!c){c={id:uid(),name:r.categoryName||'Varie / Altro',budget:0,type:'expense',kind:'variable',color:COLORS[categories.length%COLORS.length]};categories.push(c)}categoryId=c.id}transactions.push({...r,categoryId});}return{...d,categories,transactions:[...transactions,...d.transactions],settings:{...d.settings,dirtyCount:(d.settings?.dirtyCount||0)+1}}});alert('Importazione completata. I duplicati rilevati sono stati saltati.');setPreview(null)};
 const applyRecurrences=()=>{let added=0;setData(d=>{const out=[...d.transactions];for(const r of d.recurrences||[]){if(!r.active)continue;const date=`${month}-${String(Math.min(r.day,daysInMonth(month))).padStart(2,'0')}`;const key=`${date}|${r.description}|${r.amount}|${r.type}`;if(!out.some(t=>`${t.date}|${t.description}|${t.amount}|${t.type}`===key)){out.push({id:uid(),date,description:r.description,categoryId:r.categoryId,type:r.type,amount:r.amount,notes:'Ricorrenza automatica'});added++}}return{...d,transactions:out}});alert(added?`Aggiunte ${added} ricorrenze per il mese.`:'Nessuna ricorrenza da aggiungere.');};
 if(locked)return <LockScreen pin={data.settings.pin} pinTry={pinTry} setPinTry={setPinTry} unlock={()=>pinTry===data.settings.pin?setLocked(false):alert('PIN errato')}/>;
 return <div className="app"><header className="top"><div><h1>BudgetFlow</h1><p>{new Date(month+'-01').toLocaleDateString('it-IT',{month:'long',year:'numeric'})}</p></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></header>{due&&<div className="backupBanner"><ShieldCheck size={18}/><span>Non fai un backup da 7 giorni. Vuoi salvare ora su iCloud Drive?</span><button onClick={makeBackup}>Salva backup</button></div>}<main className="content">{tab==='dashboard'&&<Dashboard stats={stats} prev={prev} month={month} cats={cats} setTab={setTab}/>} {tab==='transactions'&&<Transactions tx={monthTx} cats={cats} selected={selected} setSelected={setSelected} query={query} setQuery={setQuery} onAdd={()=>setModal({type:'tx'})} onEdit={t=>setModal({type:'tx',tx:t})} onDelete={delTx} onDup={duplicate} exportCsv={exportCsv} importCsv={prepareCsv}/>} {tab==='categories'&&<Categories cats={cats} saveCat={saveCat} delCat={delCat} edit={c=>setModal({type:'cat',cat:c})} add={()=>setModal({type:'cat'})} copyPrevBudget={copyPrevBudget}/>} {tab==='recurrences'&&<Recurrences data={data} cats={cats} setData={setData} applyRecurrences={applyRecurrences}/>} {tab==='reports'&&<Reports stats={stats} txAll={txAll} cats={cats} month={month} prev={prev}/>} {tab==='backup'&&<Backup lastB={lastB} dirty={data.settings?.dirtyCount||0} makeBackup={makeBackup} restoreBackup={restoreBackup} data={data} setData={setData}/>}</main><button className="fab" onClick={()=>setModal({type:'quick'})}><Plus/></button><nav className="bottom"><Tab id="dashboard" tab={tab} setTab={setTab} icon={<LayoutDashboard/>} label="Home"/><Tab id="transactions" tab={tab} setTab={setTab} icon={<ListChecks/>} label="Movimenti"/><Tab id="categories" tab={tab} setTab={setTab} icon={<Tags/>} label="Budget"/><Tab id="recurrences" tab={tab} setTab={setTab} icon={<Repeat/>} label="Ricorrenze"/><Tab id="backup" tab={tab} setTab={setTab} icon={<FileJson/>} label="Backup"/></nav>{modal?.type==='tx'&&<TxModal tx={modal.tx} cats={cats} save={saveTx} close={()=>setModal(null)}/>} {modal?.type==='quick'&&<QuickAdd cats={cats} last={data.settings?.lastCategoryId} txAll={txAll} save={saveTx} close={()=>setModal(null)}/>} {modal?.type==='cat'&&<CatModal cat={modal.cat} save={saveCat} close={()=>setModal(null)}/>} {modal?.type==='backupReminder'&&<Reminder makeBackup={makeBackup} close={()=>setModal(null)}/>} {preview&&<CsvPreview preview={preview} close={()=>setPreview(null)} confirm={confirmImport}/>}</div>
}
function Tab(p){return <button className={p.tab===p.id?'active':''} onClick={()=>p.setTab(p.id)}>{React.cloneElement(p.icon,{size:20})}<span>{p.label}</span></button>}
function LockScreen({pinTry,setPinTry,unlock}){return <div className="lock"><Lock size={42}/><h1>BudgetFlow</h1><p>Inserisci il PIN locale</p><input value={pinTry} onChange={e=>setPinTry(e.target.value)} type="password" inputMode="numeric" autoFocus/><button onClick={unlock}>Sblocca</button></div>}
function Card({title,value,sub,cls}){return <div className={'stat '+cls}><div><p>{title}</p><h2>{value}</h2><span>{sub}</span></div></div>}
function Dashboard({stats,prev,cats,setTab}){const positive=stats.byCat.filter(c=>c.spent>0);const circumference=2*Math.PI*72;let offset=0;return <><section className="stats"><Card cls="blue" title="Uscite" value={eur(stats.spent)} sub={`${Math.round(stats.budget?stats.spent/stats.budget*100:0)}% del budget`}/><Card cls="green" title="Budget" value={eur(stats.budget)} sub="Somma categorie"/><Card cls="yellow" title="Rimanente" value={eur(stats.remaining)} sub="Disponibile"/><Card cls="purple" title="Accrediti" value={eur(stats.income)} sub="Entrate del mese"/></section><section className="grid"><div className="panel"><h2>Distribuzione spese</h2><div className="donutWrap"><svg viewBox="0 0 180 180" className="donut">{positive.map(c=>{const dash=c.share/100*circumference;const el=<circle key={c.id} cx="90" cy="90" r="72" fill="none" stroke={c.color} strokeWidth="22" strokeDasharray={`${dash} ${circumference-dash}`} strokeDashoffset={-offset} strokeLinecap="butt"/>;offset+=dash;return el})}<circle cx="90" cy="90" r="50" fill="var(--card)"/><text x="90" y="86" textAnchor="middle" className="donutTotal">{eur(stats.spent)}</text><text x="90" y="105" textAnchor="middle" className="donutSub">spese</text></svg></div><div className="legend compact">{positive.slice(0,8).map(c=><div key={c.id}><span style={{background:c.color}}/><b>{c.name}</b><strong>{eur(c.spent)}</strong><em>{c.share.toFixed(1)}%</em></div>)}</div></div><div className="panel"><h2>Spese per categoria</h2><CategoryBars items={positive}/></div></section><section className="panel"><div className="sectionTitle"><h2>Riepilogo intelligente</h2><button onClick={()=>setTab('reports')}>Report <ChevronRight size={16}/></button></div><div className="insights"><Insight text={`Ti restano ${eur(stats.remaining)}. Puoi spendere circa ${eur(Math.max(0,stats.remaining)/(daysInMonth(monthKey())-dayOfMonth()+1))} al giorno fino a fine mese.`}/>{stats.byCat.filter(c=>c.spent>prev[c.id]&&prev[c.id]).slice(0,2).map(c=><Insight key={c.id} text={`Hai speso ${eur(c.spent-prev[c.id])} in più in ${c.name} rispetto al mese scorso.`}/>)}</div></section><section className="panel"><h2>Budget vs speso</h2><div className="budgetList">{stats.byCat.map(c=><div key={c.id} className="budgetRow"><div><span style={{background:c.color}}/>{c.name}</div><strong>{eur(c.spent)} / {eur(c.budget)}</strong><div className="track"><i style={{width:`${Math.min(100,c.pct)}%`,background:c.pct>=100?'#ef4444':c.pct>=80?'#facc15':'#22c55e'}}/></div></div>)}</div></section></>}
function CategoryBars({items}){const max=Math.max(1,...items.map(i=>i.spent));return <div className="mobileBars">{items.map(i=><div key={i.id} className="mbar"><div className="mbarTop"><span style={{background:i.color}}/>{i.name}<b>{eur(i.spent)}</b></div><div className="track"><i style={{width:`${i.spent/max*100}%`,background:i.color}}/></div></div>)}</div>}
function Insight({text}){return <div className="insight"><CheckCircle2 size={18}/>{text}</div>}
function Transactions({tx,cats,selected,setSelected,query,setQuery,onAdd,onEdit,onDelete,onDup,exportCsv,importCsv}){const filtered=tx.filter(t=>norm(t.description).includes(norm(query))||norm(cats.find(c=>c.id===t.categoryId)?.name).includes(norm(query)));const file=useRef();return <section className="panel trans"><div className="sectionTitle"><h2>Transazioni</h2><div className="actions"><button onClick={exportCsv}><Download size={16}/>CSV</button><button onClick={()=>file.current.click()}><Upload size={16}/>Importa</button><input hidden ref={file} type="file" accept=".csv,text/csv" onChange={e=>importCsv(e.target.files[0])}/><button className="primary" onClick={onAdd}><Plus size={16}/>Nuova</button></div></div><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Cerca descrizione o categoria" value={query} onChange={e=>setQuery(e.target.value)}/></div>{selected.length>0&&<button className="danger" onClick={()=>onDelete(selected)}><Trash2 size={16}/>Elimina {selected.length}</button>}</div>{filtered.length===0?<div className="empty">Nessuna transazione. Tocca + per aggiungere una spesa in pochi secondi.</div>:<div className="txCards">{filtered.map(t=>{const c=cats.find(c=>c.id===t.categoryId);return <div key={t.id} className="txCard"><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,t.id]:s.filter(x=>x!==t.id))}/><div className="dot" style={{background:t.type==='income'?'#a855f7':c?.color}}/><div className="txMain"><b>{t.description}</b><span>{new Date(t.date).toLocaleDateString('it-IT')} · {t.type==='income'?'Accrediti':c?.name}</span></div><strong className={t.type}>{t.type==='income'?'+':'-'}{eur(t.amount)}</strong><button onClick={()=>onDup(t)}><Copy size={16}/></button><button onClick={()=>onEdit(t)}>Modifica</button></div>)})}</div>}</section>}
function TxModal({tx,cats,save,close}){const [f,setF]=useState(tx||{date:today(),description:'',categoryId:cats[0]?.id,type:'expense',amount:'',notes:''});return <div className="modal"><form className="sheet" onSubmit={e=>{e.preventDefault();save({...f,amount:parseEuro(f.amount)})}}><button className="x" type="button" onClick={close}><X/></button><h2>{tx?'Modifica':'Nuova'} transazione</h2><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/><input placeholder="Descrizione" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input inputMode="decimal" placeholder="Importo" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><select value={f.type} onChange={e=>setF({...f,type:e.target.value,categoryId:e.target.value==='income'?'income':cats[0]?.id})}><option value="expense">Uscita</option><option value="income">Entrata</option></select>{f.type==='expense'&&<select value={f.categoryId} onChange={e=>setF({...f,categoryId:e.target.value})}>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<textarea placeholder="Note" value={f.notes||''} onChange={e=>setF({...f,notes:e.target.value})}/><button className="primary">Salva</button></form></div>}
function QuickAdd({cats,last,txAll,save,close}){const [amount,setAmount]=useState('');const [desc,setDesc]=useState('');const [cat,setCat]=useState(last||cats[0]?.id);useEffect(()=>{const n=norm(desc);const match=cats.find(c=>n.includes(norm(c.name).split(' ')[0])||(['netflix','spotify','icloud'].some(k=>n.includes(k))&&norm(c.name).includes('abbon'))||(['esselunga','conad','coop'].some(k=>n.includes(k))&&norm(c.name).includes('spesa')));if(match)setCat(match.id)},[desc]);return <div className="modal"><form className="sheet quick" onSubmit={e=>{e.preventDefault();save({date:today(),description:desc||cats.find(c=>c.id===cat)?.name,categoryId:cat,type:'expense',amount:parseEuro(amount),notes:''})}}><button className="x" type="button" onClick={close}><X/></button><h2>Aggiungi spesa</h2><input className="bigAmount" autoFocus inputMode="decimal" placeholder="0,00 €" value={amount} onChange={e=>setAmount(e.target.value)}/><input placeholder="Descrizione opzionale" value={desc} onChange={e=>setDesc(e.target.value)}/><div className="chips">{cats.slice(0,10).map(c=><button type="button" className={cat===c.id?'sel':''} key={c.id} onClick={()=>setCat(c.id)}><span style={{background:c.color}}/>{c.name}</button>)}</div><button className="primary">Salva spesa</button></form></div>}
function Categories({cats,saveCat,delCat,edit,add,copyPrevBudget}){return <section className="panel"><div className="sectionTitle"><h2>Budget categorie</h2><div className="actions"><button onClick={copyPrevBudget}>Copia mese scorso</button><button className="primary" onClick={add}><Plus size={16}/>Nuova</button></div></div><div className="catGrid">{cats.map(c=><div className="catCard" key={c.id}><span style={{background:c.color}}/><div><b>{c.name}</b><p>{c.kind==='fixed'?'Fissa':'Variabile'} · {eur(c.budget)}</p></div><button onClick={()=>edit(c)}>Modifica</button><button onClick={()=>delCat(c.id)}><Trash2 size={16}/></button></div>)}</div></section>}
function CatModal({cat,save,close}){const [f,setF]=useState(cat||{name:'',budget:'',type:'expense',kind:'variable',color:COLORS[0]});return <div className="modal"><form className="sheet" onSubmit={e=>{e.preventDefault();save({...f,budget:parseEuro(f.budget)})}}><button className="x" type="button" onClick={close}><X/></button><h2>Categoria</h2><input placeholder="Nome" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input inputMode="decimal" placeholder="Budget mensile" value={f.budget} onChange={e=>setF({...f,budget:e.target.value})}/><select value={f.kind} onChange={e=>setF({...f,kind:e.target.value})}><option value="variable">Variabile</option><option value="fixed">Fissa</option></select><input type="color" value={f.color} onChange={e=>setF({...f,color:e.target.value})}/><button className="primary">Salva</button></form></div>}
function Recurrences({data,cats,setData,applyRecurrences}){const [f,setF]=useState({description:'',amount:'',day:1,type:'expense',categoryId:cats[0]?.id,active:true});const save=()=>{setData(d=>({...d,recurrences:[...d.recurrences,{...f,id:uid(),amount:parseEuro(f.amount),day:Number(f.day)}]}));setF({...f,description:'',amount:''})};return <section className="panel"><div className="sectionTitle"><h2>Ricorrenze</h2><button className="primary" onClick={applyRecurrences}>Applica al mese</button></div><div className="recForm"><input placeholder="Descrizione" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input placeholder="Importo" inputMode="decimal" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><input type="number" min="1" max="31" value={f.day} onChange={e=>setF({...f,day:e.target.value})}/><select value={f.categoryId} onChange={e=>setF({...f,categoryId:e.target.value})}><option value="income">Accrediti</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={save}>Aggiungi</button></div><div className="txCards">{(data.recurrences||[]).map(r=><div className="txCard" key={r.id}><CalendarClock/><div className="txMain"><b>{r.description}</b><span>Giorno {r.day} · {cats.find(c=>c.id===r.categoryId)?.name||'Accrediti'}</span></div><strong>{eur(r.amount)}</strong><button onClick={()=>setData(d=>({...d,recurrences:d.recurrences.filter(x=>x.id!==r.id)}))}><Trash2 size={16}/></button></div>)}</div></section>}
function Reports({stats,txAll,cats,month,prev}){const last6=[...Array(6)].map((_,i)=>{const d=new Date(Number(month.slice(0,4)),Number(month.slice(5,7))-1-i,1);const m=monthKey(d);const spent=txAll.filter(t=>t.type==='expense'&&String(t.date).startsWith(m)).reduce((s,t)=>s+Number(t.amount),0);return{m,spent}}).reverse();const fixed=stats.byCat.filter(c=>c.kind==='fixed').reduce((s,c)=>s+c.spent,0);return <section className="panel"><h2>Report utili</h2><div className="reportGrid"><Insight text={`Spese fisse: ${eur(fixed)} · variabili: ${eur(stats.spent-fixed)}.`}/><Insight text={`Media giornaliera spese: ${eur(stats.spent/dayOfMonth())}.`}/><Insight text={`Previsione fine mese: ${eur(stats.spent/dayOfMonth()*daysInMonth(month))}.`}/>{stats.byCat.filter(c=>c.pct>=80).map(c=><Insight key={c.id} text={`${c.name} è al ${Math.round(c.pct)}% del budget.`}/>)}</div><h3>Ultimi 6 mesi</h3><div className="budgetList">{last6.map(x=><div className="budgetRow" key={x.m}><div>{x.m}</div><strong>{eur(x.spent)}</strong><div className="track"><i style={{width:`${Math.min(100,x.spent/Math.max(1,...last6.map(z=>z.spent))*100)}%`}}/></div></div>)}</div></section>}
function Backup({lastB,dirty,makeBackup,restoreBackup,data,setData}){const file=useRef();return <section className="panel"><h2>Backup & sicurezza</h2><div className="backupBox"><p><b>Ultimo backup:</b> {lastB?new Date(lastB).toLocaleString('it-IT'):'mai'}</p><p><b>Modifiche non salvate in backup:</b> {dirty}</p><button className="primary" onClick={makeBackup}><Download size={16}/>Esporta backup completo</button><button onClick={()=>file.current.click()}><RotateCcw size={16}/>Ripristina backup</button><input hidden type="file" accept=".json" ref={file} onChange={e=>restoreBackup(e.target.files[0])}/></div><PinSettings data={data} setData={setData}/></section>}
function PinSettings({data,setData}){const [pin,setPin]=useState('');return <div className="backupBox"><h3>PIN locale</h3><p>Protegge l’apertura su questo dispositivo. Non è sincronizzato.</p><input placeholder="Nuovo PIN" type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)}/><button onClick={()=>{setData(d=>({...d,settings:{...d.settings,pin}}));alert(pin?'PIN impostato':'PIN rimosso')}}>{pin?'Imposta PIN':'Rimuovi PIN'}</button></div>}
function Reminder({makeBackup,close}){return <div className="modal"><div className="sheet"><h2>Backup consigliato</h2><p>Non fai un backup da 7 giorni. Vuoi salvare ora su iCloud Drive?</p><button className="primary" onClick={makeBackup}>Salva backup</button><button onClick={close}>Più tardi</button></div></div>}
function CsvPreview({preview,close,confirm}){return <div className="modal"><div className="sheet large"><button className="x" onClick={close}><X/></button><h2>Anteprima import CSV</h2><p>{preview.rows.length} righe rilevate · {preview.duplicates} possibili duplicati verranno saltati.</p><div className="preview">{preview.rows.slice(0,20).map(r=><div key={r.id}><span>{r.date}</span><b>{r.description}</b><span>{r.categoryName}</span><strong>{eur(r.amount)}</strong></div>)}</div><button className="primary" onClick={confirm}>Importa senza duplicati</button></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
